# torch basics

In [2]:
import torch
import torch.nn as nn
import numpy as np 
import time 

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cuda


In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-65,  18, -59,  28, -71,  94])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2, 3)  # torch.empty fonksiyonunu kullanarak, belirtilen boyutlarda (shape) boş bir tensor oluşturur. Oluşturulan tensorün değerleri başlangıçta rastgele olacaktır ve bu değerlerin spesifik bir başlangıç değeri yoktur. Yani, tensor, bellekteki mevcut değerlere bağlı olarak önceden belirlenmiş olacaktır.
input

tensor([[0.0000e+00, 4.5733e-41, 2.7340e+20],
        [6.8589e+22, 1.5766e-19, 1.4600e-19]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3, 10, steps=5) #3ten 10 a kadar eşit aralıkta artan 5 adet sayı üretir
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=-10, end=10, steps=5) #-10 ile 10 arasında logaritmik bir ölçekte beş adet örnek üretecektir. 
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [4]:
#Birim matris (identity matrix), ana köşegeni boyunca 1'ler ve geri kalan elemanları 0 olan kare bir matristir.

eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

#torch.empty_like fonksiyonu, belirli bir tensörün boyutlarına ve veri tipine sahip, ancak başlangıç değerlerine sahip olmayan bir başka tensör oluşturur. 
#Önceki tensörün boyutları ve veri tipi, yeni oluşturulan tensörün boyutları ve veri tipini belirlemede kullanılır.

tensor([[3616445622929465956, 6067247193166720308, 3761695571731690033],
        [6501004551900181550, 7309453675965983778, 8315168162784306286]])

In [8]:
#torch.cat fonksiyonu, bir veya daha fazla tensor'ü belirtilen boyutlar boyunca birleştirmek için kullanılır.
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)   #dim=0 parametresi, birleştirmenin 0. boyutta (satırlar boyunca) yapılacağını belirtir. 
out

tensor([1, 2, 3, 4, 5])

In [16]:
#tril fonksiyonu, bir tensorün üst üçgen (diagonal üstü) elemanlarını sıfırlar.
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
#triu fonksiyonu, bir tensorün alt üçgen (diagonal altı) elemanlarını sıfırlar.
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [9]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

#torch.zeros(5, 5): 5x5 boyutunda bir matris oluşturur, tüm elemanları 0 olan bir matristir.
#torch.tril(torch.ones(5, 5)) == 0: torch.tril fonksiyonu ile bu matrisin üst üçgenini maskeler. == 0 karşılaştırması, sadece üst üçgenin elemanlarını 0 olarak ayarlar ve alt üçgeni 1 olarak bırakır.
#torch.zeros(5, 5).masked_fill(..., float('-inf')): masked_fill fonksiyonu, belirli bir maskeye (torch.tril ile oluşturulan maske) dayalı olarak bir matrisin belirli elemanlarını belirtilen değerle doldurur. 
#Burada, üst üçgeni (torch.tril tarafından oluşturulan maske) float('-inf') ile doldurulur.

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)
# torch.exp fonksiyonunu kullanarak bir tensorün her elemanının üs alma işlemiyle e^x'e (euler sayısı üzeri x) yükseltilmesini gerçekleştirir.

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
#transpose fonksiyonu, tensorün boyutlarını belirtilen şekilde değiştirmeye olanak tanır.

input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2) #input tensorünün boyutlarını 0. boyut ile 2. boyutu yer değiştirerek yeni bir tensor oluşturur.
out.shape

torch.Size([4, 3, 2])

In [21]:
#torch.stack fonksiyonu, belirtilen boyut boyunca tensorleri birleştirmek için kullanılır. 
#Bu fonksiyon, bir boyut ekleyerek tensorleri üst üste yığar.

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

#stack the ytensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
#bir örnek tensor (sample) oluşturuluyor ve ardından nn.Linear modülü kullanılarak bir lineer dönüşüm (linear) yapılıyor.

import torch.nn as nn 
sample = torch.tensor([10., 10., 10.])

#nn.Linear modülü, bir giriş boyutunu belirleyen in_features ve bir çıkış boyutunu belirleyen out_features parametreleri ile tanımlanır. 
#Ayrıca, eğer bir bias eklemek istemiyorsanız, bias parametresini False olarak belirtebilirsiniz (bu durumda, bias eklenmez).
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-4.0439, -5.7986, -1.4153], grad_fn=<SqueezeBackward3>)


In [23]:
import torch.nn.functional as F 

#create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

#softmax işlemi içinde exp (e^x)(e=2.71) fonksiyonu kullanılır. 
#Softmax fonksiyonu, her öğeyi exp fonksiyonuna geçirip, ardından normalleştirme yaparak çalışır. 

print(softmax_output)

#https://youtu.be/UU1WVnMk4E8?si=OKCRnL1v6iu4nfPL&t=3738

tensor([0.0900, 0.2447, 0.6652])


In [2]:
#EMBEDDING

#initialize an embedding layer
vocab_size = 1000 #kelime dağarcığı boyutu
embedding_dim = 100 #gömme matrisi boyutu ve özellik boyutu
embedding = nn.Embedding(vocab_size, embedding_dim)  #gömme matrisi oluşturma

#create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#apply the embedding layer
embedding_output = embedding(input_indices)

#the output will be a tensor of shape (4, 100), 
#where 4 is the number of inputs and 100 is the dimensionalty of the embedding vectors

print(embedding_output.shape)

torch.Size([4, 100])


In [10]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b )  #pytorchta iki matrisin çapım işareti: @
#print(torch.matmul(a,b)) #aynı işlemin farklı şekli

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [6]:
int_64 = torch.randint(1, (3,2)).float()  #float() methodunu yazmadan çarpmaya çalıştığımızda aynı dtype olmadıkları için işlem yapılmaz
#type int64

float_32 = torch.rand(2,3)
#type float32

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
